# Generated by Django 4.2.1 on 2023-10-26 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birds',
            fields=[
                ('id_birds', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('PNG', models.ImageField(upload_to='images')),
                ('feather_color', models.TextField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ViewedUser',
            fields=[
                ('id_view', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataTime', models.DateTimeField()),
                ('id_birds', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BirdsViews.birds', unique=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BirdsViews.user')),
            ],
        ),
        migrations.AddField(
            model_name='birds',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='BirdsViews.user'),
        ),
    ]
